console.log(typeof a);
let c = 1/0;
console.log(typeof c);
let b = 'string'/2;
console.log(typeof b);
console.log(`Count: ${b}`);
console.log(`Count: ${1 + 2}`);
let msg1 = "строка \"привет\"";
console.log(msg1);
console.log(4 > 1);
let idProcess = null;
console.log(idProcess);
let arg;
console.log(arg);